// Browser-local CSV/TXT/XLSX import. JSZip is embedded in the generated HTML.
const aliases={ref:['Designator','Designators','Reference','References','RefDes','位号','元件位号'],device:['Device','Manufacturer Part Number','MPN','型号','器件型号'],footprint:['Footprint','Package','封装'],value:['Comment','Value','参数','数值'],x:['Mid X','Center X','PosX','X'],y:['Mid Y','Center Y','PosY','Y'],layer:['Layer','Side','层'],rotation:['Rotation','Rot','角度']};
const normalizeHeader=s=>String(s??'').trim().toLowerCase().replace(/[\s_\-()./]+/g,'');
function readField(row,names,required=false){for(const name of names){const entry=Object.entries(row).find(([k,v])=>normalizeHeader(k)===normalizeHeader(name)&&String(v).trim()!=='');if(entry)return String(entry[1]).trim()}if(required)throw Error('缺少字段：'+names[0]);return ''}
function parseDelimited(text,delimiter){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else if(quoted||cell==='')quoted=!quoted;else cell+=ch}else if(ch===delimiter&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);rows.push(row);row=[];cell=''}else cell+=ch}if(quoted)throw Error('CSV 引号未闭合');if(cell||row.length){row.push(cell);rows.push(row)}return rows}
function findTable(rows,placement){const required=placement?['ref','x','y','layer']:['ref'];const start=rows.findIndex(row=>required.every(key=>aliases[key].some(a=>row.some(v=>normalizeHeader(v)===normalizeHeader(a)))));if(start<0)return null;const header=rows[start].map(v=>String(v??'').trim());return rows.slice(start+1).map((values,i)=>({line:start+i+2,row:Object.fromEntries(header.map((key,j)=>[key,String(values[j]??'').trim()]).filter(([k])=>k))})).filter(({row})=>Object.values(row).some(Boolean))}
function xmlDoc(text){const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw Error('XLSX 内部 XML 无效');return doc}
const tags=(node,name)=>Array.from(node.getElementsByTagNameNS('*',name));
async function readXlsx(buffer,placement){let zip;try{zip=await JSZip.loadAsync(buffer)}catch{throw Error('无法读取 XLSX，请确认文件未加密且不是旧版 XLS 格式')}
const xml=async name=>{const entry=zip.file(name);if(!entry)throw Error('XLSX 缺少 '+name);const text=await entry.async('string');if(text.length>40e6)throw Error('工作表过大，请导出精简 CSV');return xmlDoc(text)};
const shared=zip.file('xl/sharedStrings.xml')?tags(await xml('xl/sharedStrings.xml'),'si').map(si=>tags(si,'t').map(t=>t.textContent).join('')):[];
const workbook=await xml('xl/workbook.xml'),rels=tags(await xml('xl/_rels/workbook.xml.rels'),'Relationship');
for(const sheet of tags(workbook,'sheet')){const id=sheet.getAttribute('r:id')||sheet.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id');const rel=rels.find(r=>r.getAttribute('Id')===id);if(!rel||rel.getAttribute('TargetMode')==='External')continue;const target=rel.getAttribute('Target'),parts=[];for(const p of (target.startsWith('/')?target.slice(1):'xl/'+target).split('/')){if(p==='..')parts.pop();else if(p&&p!=='.')parts.push(p)}const doc=await xml(parts.join('/'));const rows=tags(doc,'row').map(row=>{const values=[];for(const c of tags(row,'c')){const ref=c.getAttribute('r')||'',letters=ref.match(/^[A-Z]+/i)?.[0];let index=0;if(letters){for(const letter of letters.toUpperCase())index=index*26+letter.charCodeAt(0)-64;index--}else index=values.length;if(index>16383)throw Error('XLSX 列索引无效');const value=tags(c,'v')[0]?.textContent??'';const type=c.getAttribute('t');if(type==='e')throw Error('XLSX 单元格 '+ref+' 含错误值');values[index]=type==='s'?(shared[Number(value)]??''):type==='inlineStr'?tags(c,'t').map(t=>t.textContent).join(''):value}return Array.from(values,v=>v??'')});const table=findTable(rows,placement);if(table)return table}
throw Error(placement?'XLSX 找不到含位号、X/Y 坐标和层的表头':'XLSX 找不到 BOM 位号表头')}
function validateImportFile(file){if(!file)throw Error('请选择坐标文件');if(/\.pdf$/i.test(file.name))throw Error('不能导入 PDF 布局图。请从 PCB 软件导出贴片坐标文件（CSV / TXT / XLSX），需包含位号、X/Y 坐标和层。');if(!/\.(csv|txt|tsv|xlsx)$/i.test(file.name))throw Error('支持 CSV、TXT、TSV、XLSX；旧版 XLS 请另存为 XLSX');if(file.size>20*1024*1024)throw Error('单个文件不能超过 20 MB')}
async function readImportFile(file,placement){validateImportFile(file);const buffer=await file.arrayBuffer();if(/\.xlsx$/i.test(file.name))return readXlsx(buffer,placement);if(!/\.(csv|txt|tsv)$/i.test(file.name))throw Error('支持 CSV、TXT、TSV、XLSX；旧版 XLS 请另存为 XLSX');const bytes=new Uint8Array(buffer);let text;try{if(bytes[0]===255&&bytes[1]===254)text=new TextDecoder('utf-16le',{fatal:true}).decode(buffer);else if(bytes[0]===254&&bytes[1]===255)text=new TextDecoder('utf-16be',{fatal:true}).decode(buffer);else text=new TextDecoder('utf-8',{fatal:true}).decode(buffer)}catch{text=new TextDecoder('gb18030',{fatal:true}).decode(buffer)}for(const sep of [',','\t',';']){let rows;try{rows=parseDelimited(text.replace(/^\uFEFF/,''),sep)}catch{continue}const table=findTable(rows,placement);if(table)return table}throw Error(placement?'找不到坐标表头：需要 Designator、Mid X、Mid Y、Layer（或对应中文字段）':'找不到 BOM 位号表头')}
function importCoordinate(value){const m=String(value).match(/^\s*([+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:e[+-]?\d+)?)\s*(mm|mil|in|inch)?\s*$/i);if(!m)throw Error('无效坐标：'+value);const n=Number(m[1])*({mm:1,mil:.0254,in:25.4,inch:25.4}[m[2]?.toLowerCase()]||1);if(!Number.isFinite(n)||Math.abs(n)>1e7)throw Error('坐标超出有效范围');return n}
function parsePlacementTable(table){const seen=new Set();const result=table.map(({row,line})=>{try{const designator=readField(row,aliases.ref,true).toUpperCase();if(seen.has(designator))throw Error('重复位号：'+designator);seen.add(designator);const side=readField(row,aliases.layer,true).toLowerCase().replace(/\s+/g,'');const layer=({t:'Top',top:'Top',toplayer:'Top','f.cu':'Top',顶层:'Top',顶面:'Top',b:'Bottom',bottom:'Bottom',bottomlayer:'Bottom','b.cu':'Bottom',底层:'Bottom',底面:'Bottom'})[side];if(!layer)throw Error('未知层：'+side);const rotation=Number(readField(row,aliases.rotation)||0);if(!Number.isFinite(rotation))throw Error('旋转角度无效');return {designator,device:readField(row,aliases.device),value:readField(row,aliases.value),footprint:readField(row,aliases.footprint),x:importCoordinate(readField(row,aliases.x,true)),y:importCoordinate(readField(row,aliases.y,true)),layer,rotation,bom:row}}catch(e){throw Error('坐标第 '+line+' 行：'+e.message)}});if(!result.length)throw Error('坐标文件没有元件');if(result.length>20000)throw Error('最多支持 20000 个元件');return result}
function expandImportRefs(text){const refs=[];for(const token of text.replace(/\s*([-~–])\s*/g,'$1').split(/[,;，；\s]+/).filter(Boolean)){const m=token.match(/^([a-z]+)(\d+)[-~–]([a-z]*)(\d+)$/i);if(m){if((m[3]&&m[1].toUpperCase()!==m[3].toUpperCase())||+m[4]<+m[2]||+m[4]-m[2]>20000)throw Error('无效位号范围：'+token);for(let n=+m[2];n<=+m[4];n++)refs.push(m[1].toUpperCase()+n)}else refs.push(token.toUpperCase())}return refs}
function mergeImportBom(rows,table){const mapping=new Map();for(const {row,line} of table){for(const ref of expandImportRefs(readField(row,aliases.ref,true))){if(mapping.has(ref))throw Error('BOM 第 '+line+' 行重复位号：'+ref);mapping.set(ref,row)}}let matched=0;const known=new Set(rows.map(c=>c.designator));for(const c of rows){const row=mapping.get(c.designator);if(!row)continue;matched++;for(const k of ['device','value','footprint'])c[k]=readField(row,aliases[k])||c[k];c.bom={...c.bom,...row}}if(!matched)throw Error('BOM 与坐标文件没有匹配的位号，请检查是否为同一块板');return {matched,missing:rows.length-matched,extra:[...mapping.keys()].filter(r=>!known.has(r)).length}}
function boardIdentity(rows){return JSON.stringify(rows.map(c=>[c.designator,c.x,c.y,c.layer,c.rotation]).sort((a,b)=>a[0].localeCompare(b[0])))}
async function importBoardId(rows,name){const identity=boardIdentity(rows);if(identity===boardIdentity(embeddedData.components)&&name===embeddedData.name)return embeddedData.id;const bytes=new TextEncoder().encode(name+'\n'+identity);let hash=0x6c62272e07bb014262b821756295c58dn;for(const byte of bytes)hash=BigInt.asUintN(128,(hash^BigInt(byte))*0x1000000000000000000013bn);return 'import-'+hash.toString(16).padStart(32,'0')}
function resetBoard(next){data=next;components=data.components;key='pcb-placement-v1:'+data.id;done=new Set();storageOK=true;try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))done=new Set(saved.filter(r=>components.some(c=>c.designator===r&&!isTestPoint(c))))}catch{storageOK=false}buildMaterialInfo();grouped=components.some(c=>resolvedMaterialValue(c)||c.device);groups.clear();for(const c of components){c.kind=category(c);c.size=size(c);if(isTestPoint(c))continue;const k=grouped?groupKey(c):c.designator;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(c)}xmin=components.length?Math.min(...components.map(c=>c.x-c.size[0]/2))-4:0;xmax=components.length?Math.max(...components.map(c=>c.x+c.size[0]/2))+4:100;ymin=components.length?Math.min(...components.map(c=>-c.y-c.size[1]/2))-4:0;ymax=components.length?Math.max(...components.map(c=>-c.y+c.size[1]/2))+4:70;selected.clear();fuzzySelected.clear();activeGroup=null;current=null;view=null;drag=null;moved=false;layer=!components.length||components.some(c=>c.layer==='Top')?'Top':'Bottom';$('search').value='';$('type').value='';$('unfinished').checked=false;$('clickdone').checked=false;$('bothsides').checked=false;$('mirror').value='mirror';$('footprint').replaceChildren();const all=document.createElement('option');all.value='';all.textContent='所有封装';$('footprint').append(all);for(const fp of [...new Set(components.map(c=>c.footprint))].filter(Boolean).sort()){const o=document.createElement('option');o.value=fp;o.textContent=fp;$('footprint').append(o)}$('footprint').value='';$('filename').textContent=components.length?data.name+' · '+components.length+' 个元件':'未导入板子';render();fit()}
function serializeBoard(board){return JSON.stringify({id:board.id,name:board.name,components:board.components.map(({kind,size,...c})=>c)})}
function setupImport(){
for(const id of ['placement-file','bom-file'])$(id).onchange=()=>{try{for(const field of ['placement-file','bom-file']){const file=$(field).files[0];if(file)validateImportFile(file)}$('import-error').textContent=$('placement-file').files[0]?'文件已选择，请点击下方“导入并切换”。':''}catch(e){$('import-error').textContent=e.message}};
$('import-open').onclick=()=>{$('import-error').textContent='';$('import-dialog').showModal()};$('import-close').onclick=()=>$('import-dialog').close();
$('import-form').onsubmit=async event=>{event.preventDefault();const submit=$('import-submit');submit.disabled=true;$('import-error').textContent='正在读取文件…';try{const file=$('placement-file').files[0],bom=$('bom-file').files[0];const rows=parsePlacementTable(await readImportFile(file,true));const name=file.name.replace(/\.[^.]+$/,'');const id=await importBoardId(rows,name);const report=bom?mergeImportBom(rows,await readImportFile(bom,false)):null;const next={id,name,components:rows};let remembered=true;try{localStorage.setItem(boardCacheKey,serializeBoard(next))}catch{remembered=false}resetBoard(next);$('import-dialog').close();$('placement-file').value='';$('bom-file').value='';const message=`已导入 ${rows.length} 个元件：顶 ${rows.filter(c=>c.layer==='Top').length} / 底 ${rows.filter(c=>c.layer==='Bottom').length}`+(report?`。BOM 匹配 ${report.matched} 个，未匹配 ${report.missing} 个，额外位号 ${report.extra} 个`:'')+(remembered?'':'。当前板无法自动记住，请下载离线 HTML');$('import-result').textContent=message;$('import-result').hidden=false;$('import-summary').hidden=false;notify('导入完成')}catch(e){$('import-error').textContent=e.message||'导入失败，请检查文件格式'}finally{submit.disabled=false}};
$('import-result-close').onclick=()=>$('import-summary').hidden=true;
}
