// Derive assembly groups without changing source values or relying on designators.
let materialInfo=new Map();
const materialText=s=>String(s||'').replace(/[µμ]/g,'u').replace(/ω/gi,'Ω').replace(/ohms?/gi,'Ω').trim();
function canonicalFootprint(c){const fp=String(c.footprint||'').toUpperCase().replace(/\s+/g,'');const chip=fp.match(/^[RCL]?(0201|0402|0603|0805|1206|1210|2010|2512)$/);return chip?chip[1]:fp}
function numericMaterial(kind,number,unit){let factor;if(kind==='C')factor={pf:1e-12,nf:1e-9,uf:1e-6,mf:1e-3,f:1}[unit.toLowerCase()];else if(kind==='L')factor={nh:1e-9,uh:1e-6,mh:1e-3,h:1}[unit.toLowerCase()];else factor=unit==='M'||unit==='MΩ'?1e6:unit==='mΩ'?1e-3:/^[kK]/.test(unit)?1e3:1;if(factor===undefined)return null;const value=Number((Number(number)*factor).toPrecision(12));if(!Number.isFinite(value)||value<0)return null;return {number:value,token:String(value),label:formatMaterial(kind,value)}}
function formatMaterial(kind,value){if(value===0)return kind==='C'?'0F':kind==='L'?'0H':'0Ω';const units=kind==='C'?[[1,'F'],[1e-3,'mF'],[1e-6,'uF'],[1e-9,'nF'],[1e-12,'pF']]:kind==='L'?[[1,'H'],[1e-3,'mH'],[1e-6,'uH'],[1e-9,'nH']]:[[1e6,'MΩ'],[1e3,'kΩ'],[1,'Ω'],[1e-3,'mΩ']];const [scale,unit]=units.find(([scale])=>value>=scale*(1-1e-10))||units.at(-1);return Number((value/scale).toPrecision(8))+unit}
function materialCandidates(kind,input){const text=materialText(input);if(!text)return [];const result=[];if(kind==='R'){const decimal=/^(\d+)([RrKkM])(\d+)(?:Ω)?$/;const m=text.match(decimal);if(m){const v=numericMaterial(kind,m[1]+'.'+m[3],m[2]);if(v)return [{...v,confident:true}]}}
const expression=kind==='C'?/(\d+(?:\.\d+)?|\.\d+)\s*(pF|nF|uF|mF|F)/gi:kind==='L'?/(\d+(?:\.\d+)?|\.\d+)\s*(nH|uH|mH|H)/gi:/(\d+(?:\.\d+)?|\.\d+)\s*(MΩ|mΩ|kΩ|KΩ|Ω|[kKM])(?=$|[^a-zA-Z])/g;
for(const m of text.matchAll(expression)){// Long digit runs glued to package geometry are ambiguous (e.g. X850100nF).
const prefix=text.slice(0,m.index),glued=/[a-zA-Z0-9]$/.test(prefix),ambiguous=glued&&!m[1].includes('.')&&m[1].length>4;if(glued&&/^[FH]$/i.test(m[2]))continue;const value=numericMaterial(kind,m[1],m[2]);if(value)result.push({...value,confident:!ambiguous,digits:m[1],unit:m[2]})}return result}
function materialFields(c){const rows=[['参数',c.value]];for(const [name,value]of Object.entries(c.bom||{})){if(/^(name|名称|名称参数|comment|value|参数|数值)$/i.test(name.trim())&&value!==c.value)rows.push([name,value])}rows.push(['型号',c.device]);return rows}
function uniqueMaterial(candidates){const unique=new Map(candidates.map(c=>[c.token,c]));return unique.size===1?[...unique.values()][0]:null}
function isSmdPassive(c){const kind=category(c),fp=String(c.footprint||'').toUpperCase();if(!['R','C'].includes(kind)||!fp)return false;const mount=Object.entries(c.bom||{}).find(([k])=>/^smd$/i.test(k))?.[1];if(/^(no|false|0|否)$/i.test(String(mount||''))||/(?:^|[-_])(TH|THT|DIP|AXIAL|RADIAL)(?:[-_]|$)/.test(fp))return false;return /^(?:[RC])?(0201|0402|0603|0805|1206|1210|2010|2512)$/.test(fp)||/^(?:R|C|RES|CAP)[-_]SMD/.test(fp)||/^(yes|true|1|是)$/i.test(String(mount||''))}
function explicitMaterial(c){const kind=category(c);for(const [field,input]of materialFields(c)){if(field==='型号')continue;const text=materialText(input);if(!/^(?:\d|\.\d)/.test(text))continue;const candidate=uniqueMaterial(materialCandidates(kind,text).filter(v=>v.confident));if(candidate)return {...candidate,source:field,explicit:true}}return null}
// Decode only a recognizable chip-size + tolerance + resistance-code segment.
function codedResistor(c,input){if(category(c)!=='R')return null;const size=canonicalFootprint(c);if(!/^(0201|0402|0603|0805|1206|1210|2010|2512)$/.test(size))return null;const text=materialText(input).replace(/\s+/g,'').toUpperCase();const m=text.match(new RegExp('(?:^|[A-Z])'+size+'[FJDGBCK]([0-9]{3,4})(?=[A-Z]|$)'));if(!m)return null;const code=m[1];return numericMaterial('R',Number(code.slice(0,-1))*10**Number(code.at(-1)),'Ω')}
function commentInference(c){const entry=Object.entries(c.bom||{}).find(([k,v])=>/^comment$/i.test(k.trim())&&String(v||'').trim());if(!entry)return null;const text=entry[1],value=uniqueMaterial(materialCandidates(category(c),text).filter(v=>v.confident))||codedResistor(c,text);return value?{...value,source:'Comment（优先于型号）',explicit:/^(?:\d|\.\d)/.test(materialText(text))&&!codedResistor(c,text)}:null}
function buildMaterialInfo(){materialInfo=new Map();const pending=[],catalog=new Map(),partValues=new Map();
for(const c of components){if(!isSmdPassive(c))continue;const kind=category(c),found=commentInference(c)||explicitMaterial(c),bucket=JSON.stringify([kind,canonicalFootprint(c)]);if(found){materialInfo.set(c.designator,{...found,kind,bucket});if(!catalog.has(bucket))catalog.set(bucket,new Set());catalog.get(bucket).add(found.token);if(c.device){const part=JSON.stringify([kind,c.device.trim(),canonicalFootprint(c)]);if(!partValues.has(part))partValues.set(part,new Map());partValues.get(part).set(found.token,found)}}else pending.push({c,kind,bucket})}
for(const {c,kind,bucket}of pending){const possibilities=[];for(const [field,text]of materialFields(c)){const coded=codedResistor(c,text);if(coded)possibilities.push({...coded,source:field+'（编码推测）'});for(const candidate of materialCandidates(kind,text)){if(candidate.confident){possibilities.push({...candidate,source:field+'（推测）'});continue}for(let start=1;start<candidate.digits.length;start++){const tail=candidate.digits.slice(start);if(tail.length>1&&tail[0]==='0')continue;const value=numericMaterial(kind,tail,candidate.unit);if(value&&catalog.get(bucket)?.has(value.token))possibilities.push({...value,source:field+'（同封装参数校验）'})}}}
let match=uniqueMaterial(possibilities);if(!match&&possibilities.length===0&&c.device){const same=partValues.get(JSON.stringify([kind,c.device.trim(),canonicalFootprint(c)]));if(same?.size===1)match={...[...same.values()][0],source:'相同型号推测'}}if(match)materialInfo.set(c.designator,{...match,kind,bucket,explicit:false})}
}
function resolvedMaterialValue(c){return materialInfo.get(c.designator)?.label||c.value||''}
function resolvedGroupKey(c){const info=materialInfo.get(c.designator);return c.value||c.device?JSON.stringify([category(c),canonicalFootprint(c),info?.explicit?info.token:c.value||'',c.device||'']):c.designator}
function isUncertainMaterial(c){return isSmdPassive(c)&&!materialInfo.get(c.designator)?.explicit}
function materialMatch(anchor,c){if(isTestPoint(anchor)||isTestPoint(c))return null;if(anchor===c)return isUncertainMaterial(c)?'fuzzy':'exact';if(resolvedGroupKey(anchor)===resolvedGroupKey(c))return isUncertainMaterial(anchor)||isUncertainMaterial(c)?'fuzzy':'exact';const a=materialInfo.get(anchor.designator),b=materialInfo.get(c.designator);if(a&&b&&a.bucket===b.bucket&&a.token===b.token&&(!a.explicit||!b.explicit))return 'fuzzy';return null}
function selectMatches(anchors,focus=anchors[0]){current=focus||null;activeGroup=current?groupKey(current):null;selected=new Set();fuzzySelected=new Set();for(const c of components){const matches=anchors.map(a=>materialMatch(a,c));if(matches.includes('exact'))selected.add(c.designator);else if(matches.includes('fuzzy')){selected.add(c.designator);if(isUncertainMaterial(c))fuzzySelected.add(c.designator)}}if(current&&isUncertainMaterial(current)){selected.add(current.designator);fuzzySelected.add(current.designator)}}
